$(".iframe-container").fadeOut(0);
$("#show-less").fadeOut(0);
$(document).ready(function(){
    $(".iframe-container:first").fadeIn(1000);
    $("#show-more").click(function(){
        $("#show-more").fadeOut("fast");
        $("#show1").fadeIn(2000);
        $("#show2").fadeIn(2000);
        $("#show-less").fadeIn(1000);
    });
    $("#show-less").click(function(){
        $("#show1").fadeOut("fast");
        $("#show2").fadeOut("fast");
        $("#show-more").fadeIn("fast");
        $("#show-less").fadeOut("fast");
    });
});